export type TSkileyLikedSong = {
  addedAt: string
  addedBy: string
  isLikedByUser: boolean
  isLocal: string // 'stream' | 'local'
  albumArtistsNames: string
  albumName: string
  albumPopularity: number
  albumRecordLabel: string
  albumReleaseDate: string
  albumType: string
  albumUpc: string
  albumUri: string
  albumUrl: string
  artistFollowers: number
  artistGenres: string
  artistName: string
  artistPopularity: number
  artistUri: string
  artistUrl: string
  secondaryArtistsNames: string
  trackDuration: string
  trackIsrc: string
  trackName: string
  trackNumber: number
  trackPopularity: number
  trackUri: string
  trackUrl: string
  trackFeatureAcousticness: number
  trackFeatureDanceability: number
  trackFeatureEnergy: number
  trackFeatureInstrumentalness: number
  trackFeatureKey: number
  trackFeatureLiveness: number
  trackFeatureLoudness: number
  trackFeatureMode: number
  trackFeatureSpeechiness: number
  trackFeatureTempo: number
  trackFeatureTimeSignature: number
  trackFeatureValence: number
}
